"""Manage the tabbyAPI inference process (exllamav3 backend).

Unlike llama-server, tabbyAPI is a persistent process: it starts with no
model, and models are loaded/unloaded at runtime through its admin HTTP API.
"""
from __future__ import annotations

import asyncio
import datetime
import json
import logging
import re

import httpx
from pydantic import BaseModel

import tabby_builder
from config import get_exl3_models_dir, get_tabby_dir, save_exl3_settings

log = logging.getLogger(__name__)

_ANSI_RE = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")


class TabbyStartRequest(BaseModel):
    """Launch spec for the tabbyAPI process itself (no model yet)."""
    port: int = 5001
    # Defaults to loopback for safety — set to "0.0.0.0" explicitly if you
    # want the inference port reachable from the LAN.
    bind_host: str = "127.0.0.1"


class TabbyLoadRequest(BaseModel):
    """Model load spec, forwarded to tabbyAPI's /v1/model/load.

    Zero/empty means "omit the field" so tabby's own default applies.
    """
    model_name: str
    max_seq_len: int = 0
    cache_size: int = 0
    cache_mode: str = ""       # exl3: "k_bits,v_bits" e.g. "6,6"; exl2: FP16/Q8/Q6/Q4
    gpu_split_auto: bool = True
    gpu_split: str = ""        # comma-separated GB per GPU, e.g. "12,24"
    tensor_parallel: bool = False
    chunk_size: int = 0
    rope_scale: float = 0.0
    prompt_template: str = ""
    vision: bool = False
    draft_model_name: str = ""
    # "mtp" = draft from the model's own MTP weights (Qwen3.5+, Gemma 4 once
    # exllamav3 supports its assistant arch). Empty = tabby's default ("model").
    draft_mode: str = ""


def _fresh_model_state() -> dict:
    return {"name": None, "status": "none",   # none | loading | loaded | error
            "progress": "", "error": None, "settings": {}}


# tabbyAPI process state
_state: dict = {
    "status": "stopped",      # stopped | starting | running | error
    "port": 5001,
    "bind_host": "127.0.0.1",
    "pid": None,
    "error": None,
    "started_at": None,
    "cmd": "",
    "api_key": None,           # surfaced so users can point OpenAI clients at tabby
    "model": _fresh_model_state(),
}

_process: asyncio.subprocess.Process | None = None
_monitor_task: asyncio.Task | None = None
_log_task: asyncio.Task | None = None
_load_task: asyncio.Task | None = None
_log_lines: list[str] = []
_LOG_MAX = 150
_health_client: httpx.AsyncClient | None = None
_admin_key: str | None = None


def get_status() -> dict:
    result = dict(_state)
    result["model"] = dict(_state["model"])
    result["log"] = "\n".join(_log_lines[-_LOG_MAX:])
    return result


def loaded_model_name() -> str | None:
    return _state["model"]["name"] if _state["model"]["status"] in ("loading", "loaded") else None


def _base_url() -> str:
    return f"http://127.0.0.1:{_state['port']}"


def _read_api_tokens() -> dict:
    """Parse tabby's api_tokens.yml (two flat 'key: value' lines) without pyyaml."""
    tokens = {}
    path = get_tabby_dir() / "api_tokens.yml"
    for line in path.read_text(encoding="utf-8").splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            tokens[k.strip()] = v.strip().strip("'\"")
    return tokens


def _admin_headers() -> dict:
    """Admin auth header, reading api_tokens.yml lazily on first use."""
    global _admin_key
    if not _admin_key:
        try:
            _admin_key = _read_api_tokens().get("admin_key")
        except OSError as e:
            raise RuntimeError(f"Cannot read tabbyAPI api_tokens.yml: {e}")
    if not _admin_key:
        raise RuntimeError("No admin_key found in tabbyAPI api_tokens.yml")
    return {"x-admin-key": _admin_key}


def _write_config_yml(req: TabbyStartRequest) -> None:
    """Generate tabby's config.yml. Config-file launch (not CLI flags) keeps
    model_dir/draft_model_dir deterministic and persists port/bind_host."""
    models_dir = get_exl3_models_dir().resolve().as_posix()
    content = (
        "# Generated by llama-cpp-webui — edits here are overwritten on each start.\n"
        "network:\n"
        f"  host: {req.bind_host}\n"
        f"  port: {req.port}\n"
        "model:\n"
        f"  model_dir: {models_dir}\n"
        "draft_model:\n"
        f"  draft_model_dir: {models_dir}\n"
    )
    (get_tabby_dir() / "config.yml").write_text(content, encoding="utf-8")


async def start(req: TabbyStartRequest) -> None:
    """Start the tabbyAPI process (no model loaded)."""
    global _process, _monitor_task, _log_task

    if _state["status"] in ("running", "starting"):
        raise RuntimeError("tabbyAPI already running. Stop it first.")

    if not tabby_builder.is_installed():
        raise FileNotFoundError("tabbyAPI is not installed. Install it first.")

    _write_config_yml(req)
    cmd = [str(tabby_builder.venv_python()), "main.py"]

    _state.update(status="starting", port=req.port, bind_host=req.bind_host,
                  error=None, api_key=None, model=_fresh_model_state())

    try:
        _process = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
            cwd=str(get_tabby_dir()),
        )
        _state["pid"] = _process.pid
        _state["cmd"] = " ".join(cmd)
        _log_lines.clear()

        _log_task = asyncio.create_task(_log_reader())
        _monitor_task = asyncio.create_task(_health_monitor(req.port))

    except Exception as e:
        log.exception("Failed to spawn tabbyAPI")
        _state.update(status="error", error=str(e), pid=None, started_at=None)
        raise


async def stop() -> None:
    """Stop the tabbyAPI process."""
    global _process, _monitor_task, _log_task, _load_task, _health_client, _admin_key

    for task in (_monitor_task, _log_task, _load_task):
        if task:
            task.cancel()
    _monitor_task = _log_task = _load_task = None

    if _process and _process.returncode is None:
        _process.terminate()
        try:
            await asyncio.wait_for(_process.wait(), timeout=10)
        except asyncio.TimeoutError:
            _process.kill()
            await _process.wait()

    if _health_client:
        await _health_client.aclose()
        _health_client = None

    _process = None
    _admin_key = None
    _state.update(status="stopped", pid=None, error=None, started_at=None,
                  cmd="", api_key=None, model=_fresh_model_state())


async def shutdown() -> None:
    """Gracefully shut down tabbyAPI resources on app exit."""
    await stop()


async def _log_reader() -> None:
    """Read tabbyAPI stdout into the ring buffer and echo to the console."""
    try:
        while _process is not None and _process.stdout is not None:
            line = await _process.stdout.readline()
            if not line:
                break  # EOF: process closed its stdout (likely exited)
            decoded = _ANSI_RE.sub("", line.decode(errors="replace")).rstrip()
            _log_lines.append(decoded)
            print(f"[tabbyAPI] {decoded}", flush=True)
            if len(_log_lines) > _LOG_MAX * 2:
                del _log_lines[:_LOG_MAX]
    except asyncio.CancelledError:
        pass


async def _health_monitor(port: int) -> None:
    """Poll tabby's /health until ready (HTTP 200 = healthy), then watch it."""
    global _health_client
    url = f"http://127.0.0.1:{port}/health"

    _health_client = httpx.AsyncClient()

    # Wait for the server to come up (no model loads at boot, so 60s is plenty)
    for _ in range(120):  # 60s at 0.5s cadence
        if _process is None or _process.returncode is not None:
            exit_code = _process.returncode if _process else "unknown"
            _state.update(status="error", error=f"Process exited (code {exit_code})")
            return

        try:
            r = await _health_client.get(url, timeout=2)
            if r.status_code == 200:
                _state.update(status="running",
                              started_at=datetime.datetime.now().isoformat())
                try:
                    _state["api_key"] = _read_api_tokens().get("api_key")
                except OSError:
                    log.warning("api_tokens.yml not readable yet; api_key shown after next status refresh")
                break
        except Exception:
            pass

        await asyncio.sleep(0.5)
    else:
        _state.update(status="error", error="tabbyAPI failed to become healthy within 60 seconds")
        return

    # Ongoing health watch. tabby's event loop stalls during downloads and
    # model loads (they run in-process), so a single missed check is normal:
    # only flag error after consecutive failures, and recover on success.
    fails = 0
    while True:
        await asyncio.sleep(5)
        if _process is None or _process.returncode is not None:
            _state.update(status="error", error="Process exited unexpectedly")
            return

        try:
            r = await _health_client.get(url, timeout=5)
            if r.status_code != 200:
                raise RuntimeError(f"Health check returned {r.status_code}")
            fails = 0
            if _state["status"] == "error":
                _state.update(status="running", error=None)
        except Exception as e:
            fails += 1
            if fails >= 3:
                _state.update(status="error", error=f"Health check failed: {e}")


# ── Model load/unload via admin API ──────────────────────

_INLINE_MARKER = "# Generated by llama-cpp-webui"


def _sync_inline_overrides(model_name: str, draft_mode: str) -> None:
    """tabby's /v1/model/load API schema has no draft_mode field, but tabby
    reads a per-model tabby_config.yml on every load — set it there."""
    path = get_exl3_models_dir() / model_name / "tabby_config.yml"
    ours = path.is_file() and path.read_text(encoding="utf-8").startswith(_INLINE_MARKER)
    if draft_mode:
        if path.is_file() and not ours:
            raise RuntimeError(f"{path} exists and wasn't written by this webui; "
                               "refusing to overwrite. Remove it or set draft_mode there.")
        path.write_text(f"{_INLINE_MARKER} — deleted when draft mode is reset\n"
                        f"draft_model:\n  draft_mode: {draft_mode}\n", encoding="utf-8")
    elif ours:
        path.unlink()


def _build_load_body(req: TabbyLoadRequest) -> dict:
    body: dict = {"model_name": req.model_name}
    if req.max_seq_len > 0:
        # exllamav3 requires seq len divisible by 256; round up
        body["max_seq_len"] = -(-req.max_seq_len // 256) * 256
    if req.cache_size > 0:
        body["cache_size"] = -(-req.cache_size // 256) * 256
    if req.cache_mode.strip():
        body["cache_mode"] = req.cache_mode.strip()
    if req.gpu_split.strip():
        body["gpu_split"] = [float(x) for x in req.gpu_split.split(",") if x.strip()]
        body["gpu_split_auto"] = False
    elif not req.gpu_split_auto:
        body["gpu_split_auto"] = False
    if req.tensor_parallel:
        body["tensor_parallel"] = True
    if req.chunk_size > 0:
        body["chunk_size"] = req.chunk_size
    if req.rope_scale > 0:
        body["rope_scale"] = req.rope_scale
    if req.prompt_template.strip():
        body["prompt_template"] = req.prompt_template.strip()
    if req.vision:
        body["vision"] = True
    if req.draft_model_name.strip():
        body["draft_model"] = {"draft_model_name": req.draft_model_name.strip()}
    return body


async def load_model(req: TabbyLoadRequest) -> None:
    """Kick off a model load; progress is reflected in status polls."""
    global _load_task

    if _state["status"] != "running":
        raise RuntimeError("tabbyAPI is not running. Start it first.")
    if _state["model"]["status"] == "loading":
        raise RuntimeError("A model is already loading.")
    if req.draft_model_name.strip() == req.model_name:
        raise ValueError("Draft model must differ from the main model")
    if req.draft_mode not in ("", "mtp", "ngram"):
        raise ValueError(f"Unknown draft mode: {req.draft_mode}")
    if req.draft_mode and req.draft_model_name.strip():
        raise ValueError("Draft model and MTP/n-gram drafting are mutually exclusive")

    # Deterministic swap: don't rely on tabby's internal unload-on-load
    if _state["model"]["status"] == "loaded":
        await unload_model()

    _sync_inline_overrides(req.model_name, req.draft_mode)
    body = _build_load_body(req)  # may raise ValueError on bad gpu_split
    _state["model"] = {"name": req.model_name, "status": "loading",
                       "progress": "requesting load…", "error": None,
                       "settings": req.model_dump()}
    _load_task = asyncio.create_task(_run_load(body))


async def _run_load(body: dict) -> None:
    model = _state["model"]
    try:
        headers = _admin_headers()
        async with httpx.AsyncClient() as client:
            async with client.stream("POST", f"{_base_url()}/v1/model/load",
                                     json=body, headers=headers, timeout=None) as r:
                if r.status_code != 200:
                    detail = (await r.aread()).decode(errors="replace")
                    raise RuntimeError(f"Load failed ({r.status_code}): {detail[:500]}")
                async for line in r.aiter_lines():
                    if not line.startswith("data:"):
                        continue
                    try:
                        event = json.loads(line[5:].strip())
                    except json.JSONDecodeError:
                        continue
                    model["progress"] = f"{event.get('module', '?')}/{event.get('modules', '?')} modules"
                    if event.get("status") == "finished":
                        model["status"] = "loaded"
                        model["progress"] = "loaded"
        if model["status"] != "loaded":
            raise RuntimeError("Load failed before completion — check the tabbyAPI log for the reason")
        try:
            save_exl3_settings(model["name"], model["settings"])
        except Exception:
            # Losing one settings save is fine; failing the load status is not.
            log.exception("Failed to persist exl3 settings for %s", model["name"])
    except asyncio.CancelledError:
        pass
    except Exception as e:
        log.exception("Model load failed")
        model.update(status="error", error=str(e))


async def unload_model() -> None:
    if _state["status"] != "running":
        raise RuntimeError("tabbyAPI is not running.")
    async with httpx.AsyncClient() as client:
        r = await client.post(f"{_base_url()}/v1/model/unload",
                              headers=_admin_headers(), timeout=30)
        if r.status_code != 200:
            raise RuntimeError(f"Unload failed ({r.status_code}): {r.text[:500]}")
    _state["model"] = _fresh_model_state()
